# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instagraminfo',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('image_ins', models.TextField()),
                ('tag_ins', models.TextField()),
            ],
        ),
    ]
